### PR TITLE
ci: add Jenkinsfile, requirements.txt and redirect

### PR DESCRIPTION
**Pull request by jakubgs**
This adds CI builds for both main branches:

* `develop` built by [CI job](https://ci.status.im/job/website/job/dev-help.status.im/) to publish to https://dev-help.status.im/
* `master` built by [CI job](https://ci.status.im/job/website/job/help.status.im/) to publish to https://help.status.im/

Changes should be made against `develop` and then once ready `master` should be rebased on `develop` to push the changes to the main site.

Related: https://github.com/status-im/infra-misc/commit/305f9445
Resolves: https://github.com/status-im/help.status.im/issues/27

### CODE REVIEW

**Comment by jorge-campo** [comment]
I'm afraid I can't make all the links work on the Status Help site build. The links only work at the / level on the main index.html file https://github.com/status-im/help.status.im/blob/develop/docs/en/index.md.

- The "Getting started section" (for example) shows the proper URL [https://dev-help.status.im/en/getting-started/](https://dev-help.status.im/en/getting-started/)
- Other docs like "Download Status for Mac" show the wrong URL [https://dev-help.status.im/help.status.im/getting-started/download-status-for-mac](https://dev-help.status.im/help.status.im/getting-started/download-status-for-mac)

I'm not controlling the URLs from within Material config at [mkdocs.yml](https://github.com/status-im/help.status.im/blob/develop/config/en/mkdocs.yml).

Note: GitHub Pages is still enabled on this repo, and I think it shouldn't be if we go with our own CI. I have removed them in other repos by setting the config to "none," according to [GitHub's help](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

**Comment by jakubgs** [comment]
@jorge-campo that has nothing to do with method of deployment and everything to do with the contents of the documents.

Look at this file:
https://github.com/status-im/help.status.im/blob/312408495b4fa5bf20ee445382bfce97a199fd63/docs/en/getting-started/index.md#L14-L15
Do you see anything wrong here? Or this one:
https://github.com/status-im/help.status.im/blob/312408495b4fa5bf20ee445382bfce97a199fd63/docs/en/getting-started/download-status-for-mac.md#L14
Please look at the format of links in Markdown:

* https://www.markdownguide.org/basic-syntax/#links
* https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages

**Comment by jorge-campo** [comment]
Hey @jakubgs, I'll add here the information we discussed for the record.

We don't use Markdown URLs in the traditional Markdown way: `[My link](https://path-to-my-link)`. Instead, we use a sort-of `includes` file that exists at the end of every Markdown document:

`--8<-- "includes/urls-en.txt"`

the `urls-en.txt` file stores the URL information for all links in the English language; this is a snippet of this text file:

```
[download-status-for-linux]: /help.status.im/getting-started/download-status-for-linux
[download-status-for-mac]: /help.status.im/getting-started/download-status-for-mac
[run-status-app-first-time]: /help.status.im/getting-started/run-status-app-first-time
```

This is supported by Material for MkDocs but, why are we doing this?  For two main reasons mainly:

- URLs depend on the document title and document path in the repo. This changes from time to time, and tracking these changes across multiple languages is prone to error.
- URLs are hard for translators; they don't know if this is something that should or shouldn't be translated. This results in less-than-perfect translations that must be reviewed.

Managing URLs is hard, and there isn't a perfect solution. But I believe that by centralizing the URLs for each language on its own `includes` file, we can reduce the burden considerably.

Notice that this is supported by Material for MkDocs through the [Snippets](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#usage) extension, and described in [other installations](https://github.com/squidfunk/mkdocs-material/discussions/2346). Notice also that this works as expected when I build the docs locally using `mkdocs gh-deploy --force` and when I use GitHub pages as part. See here:

https://user-images.githubusercontent.com/62282406/164394199-b45c41d3-019a-437b-aac6-16b6d6a20e84.mp4

This is the reason I think the build is somehow messing with this `includes/urls-en.txt` file, giving these long-and-weird URLs you mention in your message.

**Comment by jakubgs** [comment]
For future reference, the issue with the links was their definition. Before it was:
```yaml
[download-status-for-linux]: /help.status.im/getting-started/download-status-for-linux
[download-status-for-mac]: /help.status.im/getting-started/download-status-for-mac
[run-status-app-first-time]: /help.status.im/getting-started/run-status-app-first-time
```
But the correct form is just the path without the domain or the weird prefix slash:
```
[download-status-for-linux]: /en/getting-started/download-status-for-linux
[download-status-for-mac]: /en/getting-started/download-status-for-mac
[run-status-app-first-time]: /en/getting-started/run-status-app-first-time
```

**Review by jorge-campo — APPROVED** [review]
Looks good to me, @jakubgs. Thanks for all the changes and the fixes to the `edit_uri` paths.

**Pull request merged**
